# OpenAPI v3 Training Exercise

openapi: "3.0.0"
info:
  version: 1.0.0
  title: My API Spec
  description: |
    # Exercise - Markdown
    
    OpenAPI 3.0 uses the CommonMark specification for 
    `description` properties, and other properties that allow
    markdown formatting. 
    
    Reformat this description by translating the embedded
    instructions into the corresponding CommonMark syntax:
    <hr/>
    
      (Heading 1) Introducing RoboPet
      
      Have you ever wished your pet would have robot-like
      qualities? Consider the benefits:
      
      (bullet list)
        Solar powered, no feeding, walking , or cleaning up!
        Snuggly as you please, with interchangeable synthetic fur coats.
        Replaces your home smart hub, food processor and hedge trimmer 
       

    Customer API used at [Bigco](http://www.bigco.com).
  
  
paths:
  /resourceUrl:
    get:
      responses:
        200:
          description: Success